[package]
name = "presort-element-uniqueness"
version = "0.1.0"
authors = ["Daniel Buckley <buckley.daniel.n@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

libmath = "0.2.1"